services:
  - type: web
    name: fitfindr-backend
    runtime: python3
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false