services:
  - type: web
    name: fitfindr-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false